In [1]:
import numpy as np

In [2]:
# This is rank 1 array 
# But Dont't use this
a = np.random.randn(5)

In [3]:
print(a)

[-0.34139904 -0.30426941 -1.1055347   0.23649582 -0.54556768]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.34139904 -0.30426941 -1.1055347   0.23649582 -0.54556768]


In [6]:
print(np.dot(a, a.T))

1.7849145235555037


In [7]:
# This is Rank 2 Array
# Use this Array
a = np.random.randn(5,  1)
print(a)

[[ 0.26706973]
 [ 0.38925931]
 [ 0.46525623]
 [ 0.78290563]
 [-0.83912417]]


In [8]:
print(a.T)

[[ 0.26706973  0.38925931  0.46525623  0.78290563 -0.83912417]]


In [9]:
print(np.dot(a, a.T))

[[ 0.07132624  0.10395938  0.12425586  0.2090904  -0.22410467]
 [ 0.10395938  0.15152281  0.18110532  0.30475331 -0.3266369 ]
 [ 0.12425586  0.18110532  0.21646336  0.36425172 -0.39040775]
 [ 0.2090904   0.30475331  0.36425172  0.61294123 -0.65695504]
 [-0.22410467 -0.3266369  -0.39040775 -0.65695504  0.70412937]]


In [10]:
assert(a.shape == (5, 1))

In [11]:
a = a.reshape((5, 1))
print(a)

[[ 0.26706973]
 [ 0.38925931]
 [ 0.46525623]
 [ 0.78290563]
 [-0.83912417]]
